spring:
  application:
    name: tmpl
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tmplDB
    username: root
    password: password123


mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: your_secret_key
  expiration: 3600000

